/**
 * 
 */
$(document).ready(function(){
    $("button").click(function(){
        $('#imgPath').val(($(this).data('src')));
        $('#statusMsg').val($('#'+$(this).data('status')).val());
        $('#pageForm').submit();
    });
});